# modified from: transformer_wmt17_ende.yaml
name: "transformer"

data:
    src: "en"
    trg: "de"
    train: "chatnmt/official_split_line_by_line/wmt17bpe__boundaries/train.tags.bpe.wmt-ende-best"
    dev: "chatnmt/official_split_line_by_line/wmt17bpe__boundaries/dev.tags.bpe.wmt-ende-best"        # development data for validation
    test: "chatnmt/coher/coherCorrTest.tags.bpe.wmt-ende-best"
    level: "bpe"
    lowercase: False
    max_sent_length: 100
    src_vocab: "models/wmt_ende_transformer/src_vocab.txt"
    trg_vocab: "models/wmt_ende_transformer/trg_vocab.txt"

testing:
    beam_size: 1
    alpha: 1.0

training:
    random_seed: 42
    optimizer: "adam"
    normalization: "tokens"
    adam_betas: [0.9, 0.999]
    scheduling: "plateau"
    patience: 8
    decrease_factor: 0.7
    loss: "crossentropy"
    learning_rate: 0.0002
    learning_rate_min: 0.00000001
    weight_decay: 0.0
    label_smoothing: 0.1
    batch_size: 2048
    batch_type: "token"
    #eval_batch_size: 3600
    #eval_batch_type: "token"
    batch_multiplier: 1
    early_stopping_metric: "ppl"
    epochs: 50
    validation_freq: 750
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "models/wmt20/domainadaptation/main_tfm_b2048_ende_chat_finetuned_1/"
    load_model: "models/wmt20/domainadaptation/main_tfm_b2048_ende_news_pretrained/best.ckpt"
    reset_best_ckpt: True
    reset_scheduler: True
    reset_optimizer: True
    overwrite: True
    shuffle: True
    use_cuda: True
    max_output_length: 100
    print_valid_sents: [0, 1, 2, 3]
    keep_last_ckpts: 3

model:
    initializer: "xavier"
    bias_initializer: "zeros"
    init_gain: 1.0
    embed_initializer: "xavier"
    embed_init_gain: 1.0
    tied_embeddings: True
    tied_softmax: True
    encoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8
        embeddings:
            embedding_dim: 512
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 2048
        freeze: False
        dropout: 0.1
        multi_encoder: True
    decoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8
        embeddings:
            embedding_dim: 512
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 2048
        freeze: False
        dropout: 0.1
